/* eslint-disable import/prefer-default-export */

import Calendar from "app/apps/Calendar"
import ComponentMobileTemp from "app/components/common/ComponentMobileTemp"

import { IAppTemplate, IPortfolio, IPortfolioType } from "types"
import { generateRandomWidgets } from "./generators"

export const Portfolios: IPortfolio[] = [
    {
        id: 104,
        name: "InternalPortfolio",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/app-icons-placeholder.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        mobileComponent: ComponentMobileTemp,
        metadata: {
            title: "ExternalPortfolio", // The title of the app
            description: "System default launcher", // A short description or tooltip
            version: "0.0.1", // App version number
        },
        component: Calendar,
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INTERNAL,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 105,
        name: "ExternalPortfolio",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/app-icons-placeholder.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        mobileComponent: ComponentMobileTemp,
        metadata: {
            title: "ExternalPortfolio", // The title of the app
            description: "System default launcher", // A short description or tooltip
            version: "0.0.1", // App version number
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.EXTERNAL,
        exploreURL: "https://iamsal.github.io/Dhaka-Bus-Route/home.html",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 106,
        name: "EmbedPortfolio",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/app-icons-placeholder.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "EmbedPortfolio", // The title of the app
            description: "System default launcher", // A short description or tooltip
            version: "0.0.1", // App version number
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.EMBED,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
        iframeURL: "",
    },
    {
        id: 107,
        name: "InfoPortfolio",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/app-icons-placeholder.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "InfoPortfolio", // The title of the app
            description: "System default launcher", // A short description or tooltip
            version: "0.0.1", // App version number
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },

    {
        id: 330,
        name: "bdGeoHopp",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/bd-geo-hopp.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "BdGeoHopp",
            description: "Description for BdGeoHopp",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 388,
        name: "bgAi",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/bg-ai.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "BgAi",
            description: "Description for BgAi",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 639,
        name: "bodywiseGym",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/bodywise-gym.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "BodywiseGym",
            description: "Description for BodywiseGym",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 778,
        name: "covidStats",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/covid-stats.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "CovidStats",
            description: "Description for CovidStats",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 324,
        name: "damasf",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/damasf.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "Damasf",
            description: "Description for Damasf",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 565,
        name: "dan",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/dan.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "Dan",
            description: "Description for Dan",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 757,
        name: "darkoin",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/darkoin.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "Darkoin",
            description: "Description for Darkoin",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 649,
        name: "dhakaBusRoute",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/dhaka-bus-route.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "DhakaBusRoute",
            description: "Description for DhakaBusRoute",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 258,
        name: "docbotPredictor",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/docbot-predictor.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "DocbotPredictor",
            description: "Description for DocbotPredictor",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 975,
        name: "dristiAi",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/dristi-ai.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "DristiAi",
            description: "Description for DristiAi",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 140,
        name: "evepacificMedia",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/evepacific-media.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "EvepacificMedia",
            description: "Description for EvepacificMedia",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 395,
        name: "expertContractorz",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/expert-contractorz.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "ExpertContractorz",
            description: "Description for ExpertContractorz",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 233,
        name: "forksInn",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/forks-inn.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "ForksInn",
            description: "Description for ForksInn",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 671,
        name: "fruitality",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/fruitality.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "Fruitality",
            description: "Description for Fruitality",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 388,
        name: "goriberFigma",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/goriber-figma.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "GoriberFigma",
            description: "Description for GoriberFigma",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 953,
        name: "hoi",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/hoi.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "Hoi",
            description: "Description for Hoi",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 226,
        name: "konatraders",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/konatraders.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "Konatraders",
            description: "Description for Konatraders",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 240,
        name: "lightingIndex",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/lighting-index.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "LightingIndex",
            description: "Description for LightingIndex",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 546,
        name: "mirnet",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/mirnet.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "Mirnet",
            description: "Description for Mirnet",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 708,
        name: "mylifemobile",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/mylifemobile.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "Mylifemobile",
            description: "Description for Mylifemobile",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 339,
        name: "paribahan",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/paribahan.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "Paribahan",
            description: "Description for Paribahan",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 157,
        name: "puppetGround",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/puppet-ground.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "PuppetGround",
            description: "Description for PuppetGround",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 939,
        name: "simpleCalcJs",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/simple-calc-js.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "SimpleCalcJs",
            description: "Description for SimpleCalcJs",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 362,
        name: "simpleJsRunner",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/simple-js-runner.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "SimpleJsRunner",
            description: "Description for SimpleJsRunner",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 421,
        name: "smSolver",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/sm-solver.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "SmSolver",
            description: "Description for SmSolver",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 652,
        name: "smbCapitalPartners",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/smb-capital-partners.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "SmbCapitalPartners",
            description: "Description for SmbCapitalPartners",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 761,
        name: "sockettle",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/sockettle.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "Sockettle",
            description: "Description for Sockettle",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 845,
        name: "tavaas",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/tavaas.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "Tavaas",
            description: "Description for Tavaas",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 496,
        name: "teamLookup",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/team-lookup.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "TeamLookup",
            description: "Description for TeamLookup",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 836,
        name: "tuneupmaster.ca",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/tuneupmaster.ca.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "Tuneupmaster.ca",
            description: "Description for Tuneupmaster.ca",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 62,
        name: "urbanRiders",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/urban-riders.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "UrbanRiders",
            description: "Description for UrbanRiders",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 171,
        name: "verimap",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/verimap.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "Verimap",
            description: "Description for Verimap",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 30,
        name: "wbh",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/wbh.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "Wbh",
            description: "Description for Wbh",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 202,
        name: "wcit",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/wcit.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "Wcit",
            description: "Description for Wcit",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 231,
        name: "win4local",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/win4local.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "Win4local",
            description: "Description for Win4local",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
    {
        id: 894,
        name: "xiangbuGroup",
        icon: {
            svg: "/static/images/icons/ios-weather.svg",
            png: "/static/images/icons/PNG/xiangbu-group.png",
        },
        status: {},
        launcherType: "PORTFOLIO",
        supports: ["DESKTOP", "MOBILE"],
        metadata: {
            title: "XiangbuGroup",
            description: "Description for XiangbuGroup",
            version: "0.0.1",
        },
        config: {
            isHidden: false,
            initTitle: "Launchpad",
            initWindowWidth: 640,
            initWindowHeight: 480,
            startMaximized: true,
            isDefault: false,
            isPinned: false,
            template: IAppTemplate.WINDOW,
        },
        widgets: generateRandomWidgets(3, 7),
        type: IPortfolioType.INFO,
        exploreURL: "",
        gallery: [],
        tags: [],
        thumbnailPath: "",
    },
]
